[project]
name = "proxbad3"
version = "0.1.0"
description = "An automated tool for testing the security of RFID access control systems using the Proxmark3 device."
authors = [
    { name = "wh0crypt", email = "wh0crypt@computer.org" },
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "argparse>=1.4.0",
    "proxmark3py>=0.0.4",
]
